openapi: '3.0.3'
info:
  title: BCP API
  description: API di test per Bike Comfort Project.
  version: '1.0.0'
servers:
  - url: http://192.168.4.1/v1
    description: Server di Test

paths:

  /logs:
    get:
      tags:
        - Logs
      summary: Restituisce la lista di tutte le registrazioni disponibili.
      description: Ritorna una lista di nomi.
      responses:
        '200':
          description: Lista inviata correttamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    description: La lista effettiva dei nomi
                    items:
                      type: string
                  meta:
                    type: object
                    description: Metadati numero totali elementi
                    properties:
                      totalItems:
                        type: integer
        '401':
          description: Unauthorized.
    delete:
      tags:
        - Logs
      summary: Elimina TUTTE le registrazioni.
      description: Cancella tutti i file .json e .bin.
      responses:
        '204':
          description: Files deleted successfully. No content found.
        '401':
          description: Unauthorized.

  /logs/{filename}:
    delete:
      tags:
        - Logs
      summary: Elimina una specifica registrazione.
      description: Elimina i file .json e .bin con filename corrispondenti a quello fornito.
      parameters:
      - name: filename
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: File eliminato con successo.
        '401':
          description: Unauthorized.
        '404':
          description: File not found.
  /logs/{filename}/config:
    get:
      tags:
        - Logs
      summary: Scarica il file contenente la configurazione.
      description: Ritorna il file .json contenente la configurazione della registrazione indicata.
      parameters:
      - name: filename
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Configurazione in json.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/RigidBike'
                  - $ref: '#/components/schemas/HardtailBike'
                  - $ref: '#/components/schemas/FullBike'
        '401':
          description: Unauthorized.
        '404':
          description: File not found.
  /logs/{filename}/data:
    get:
      tags:
        - Logs
      summary: Scarica il payload binario.
      description: Scarica il file .bin associato. Questo stream può essere di svariati MB.
      parameters:
      - name: filename
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Stream binario dei dati.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized.
        '404':
          description: File not found.

  /config:
    put:
      tags:
        - Configuration
      summary: Aggiorna la configurazione completa della bici
      description: Sovrascrive la configurazione attuale con i nuovi parametri forniti nel body.
      requestBody:
        description: Oggetto JSON contenente tutti i parametri di setup.
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/RigidBike'
                - $ref: '#/components/schemas/HardtailBike'
                - $ref: '#/components/schemas/FullBike'
      responses:
        '200':
          description: Configuration updated successfully.
        '401':
          description: Unauthorized.

components:
  schemas:

    # Componenti riutilizzabili
    TireSetup:
      type: object
      properties:
        model:
          type: string
        setup:
          type: string
          enum: ['tube', 'tubeless', 'insert']
        pressure:
          type: number
          format: float
        pressure_unit:
          type: string
          enum: ['psi', 'bar']

    SuspensionSetup:
      type: object
      properties:
        model:
          type: string
        travel:
          type: integer
        spring:
          type: string
        pressure:
          type: integer
        sag:
          type: integer
        hsc:
          type: integer
          nullable: true
        lsc:
          type: integer
          nullable: true
        rebound:
          type: integer
        tokens:
          type: integer
          nullable: true

    # Configurazione base comune a tutte le bici
    BaseBike:
      type: object
      required: [type]
      properties:
        type:
          type: string
          enum: [Rigid, Hardtail, Full] # Discriminatore
          description: Identifica il tipo di bici
        wheels:
          type: object
          properties:
            rims:
              type: string
            material:
              type: string
        front_tire:
          $ref: '#/components/schemas/TireSetup'
        rear_tire:
          $ref: '#/components/schemas/TireSetup'
        hardware:
          type: object
          properties:
            sensor_count:
              type: integer
            sample_rate:
              type: integer

    RigidBike:
      allOf:
        - $ref: '#/components/schemas/BaseBike'
        - type: object
          properties:
            bike_geometry:
              type: object
              properties:
                frame_type:
                  type: string

    HardtailBike:
      allOf:
        - $ref: '#/components/schemas/BaseBike'
        - type: object
          properties:
            bike_geometry:
              type: object
              properties:
                frame_type:
                  type: string
                fork_travel:
                  type: integer
            fork_setup:
              $ref: '#/components/schemas/SuspensionSetup'

    FullBike:
      allOf:
        - $ref: '#/components/schemas/BaseBike'
        - type: object
          properties:
            bike_geometry:
              type: object
              properties:
                frame_type:
                  type: string
                fork_travel:
                  type: integer
                shock_travel:
                  type: integer
            fork_setup:
              $ref: '#/components/schemas/SuspensionSetup'
            shock_setup:
              $ref: '#/components/schemas/SuspensionSetup'
